### ISSUE TITLE
CVE for openssl 3.1.0

### ISSUE THREAD

**Issue by ekomarova** [conda-forge/openssl-feedstock#122]
### Comment:

The following CVE's affects v3.1.0 openssl: https://nvd.nist.gov/vuln/detail/CVE-2023-0464, https://nvd.nist.gov/vuln/detail/CVE-2023-0465, https://nvd.nist.gov/vuln/detail/CVE-2023-0466. It seems that there are already patched and the new tag 3.1.0is available that is not affected by CVE's. 

When does conda-forge plan to release a new update?

**Comment by ekomarova** [comment]
It looks like the new tag is not yet available in https://github.com/openssl/openssl, then I'll just leave it as a reminder that the current version has CVE's

**Comment by h-vetinari** [comment]
There's no new release [due to](https://www.openssl.org/news/secadv/20230322.txt) the low severity of those vulnerabilities.

I would consider a PR that backports the respective fixes, however even then I believe it's unlikely that whatever infrastructure is yelling at you could be taught that conda-forge's 3.1.0 release is not CVE-exposed. So the question becomes whether the effort is worth it.

Or of course you can go ask the OpenSSL project to prioritise a new release, but I doubt they'll change their assessment...

**Comment by yelled1** [comment]
@h-vetinari 
Severity   

CVSS 3.x Severity and Metrics:

NIST CVSS scoreNIST: NVDBase Score: [7.5 HIGH](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?name=CVE-2023-0464&vector=AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H&version=3.1&source=NIST)

Seems like 7.5 is considered `high` but not `critical` by NIST  & I am having issues with it at work. So, a bit puzzled can you elaborate or just pt me to where to read about it? I am new to CVE or CVSS.

**Comment by ekomarova** [comment]
As I understand from @h-vetinari words conda-forge can consider PR with patches, so I can create this

**Comment by yelled1** [comment]
Working for a bank & any time we see a high 7.0~ on CVE or CVSS we tag them right away & require (begging?) session(s) with security. Unfortunately, we can't go to `conda-forge` as it's a user channel.
So, I have strongly asked for Anaconda team to build packages based on openssl-3.0-SNAP-20230424:
* OpenSSL 3.0.x / 3.1.x 
* Python 3.9.16 itself as the current version cannot accommodate 3.x versions & only 1.1.1's
* bzip2 conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
* libffi conda-forge/win-64::libffi-3.4.2-h8ffe710_5
* libsqlite conda-forge/win-64::libsqlite-3.40.0-hcfcfb64_0
* libzlib conda-forge/win-64::libzlib-1.2.13-hcfcfb64_4
* tk conda-forge/win-64::tk-8.6.12-h8ffe710_0
* ucrt conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0
* xz conda-forge/win-64::xz-5.2.6-h8d14728_0

Think I understand @h-vetinari 
https://www.openssl.org/news/secadv/20230322.txt says:
OpenSSL Security Advisory [22nd March 2023]
===========================================
Excessive Resource Usage Verifying X.509 Policy Constraints (CVE-2023-0464)
===========================================================================
Severity: `Low`

However, in https://nvd.nist.gov/vuln/detail/CVE-2023-0464 CVSS 3.x Severity and Metrics says:
NIST CVSS scoreNIST: NVDBase Score: 7.5 HIGHVector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
`HIGH`

Not quite why NIST & OpenSSL's rating is different.
Is this some misclassification by NIST or am I missing something?
Anyway, I have emailed both Anaconda & NIST. Once I get an answer, I will be write back.

**Comment by h-vetinari** [comment]
> As I understand from @h-vetinari words conda-forge can consider PR with patches, so I can create this.

You can see how this is done in #124 for example (where we did this for a regression fix).

> By the way, do you have any policy regarding CVE? For example, the time frame for patching high or critical CVE? Or is conda-forge not generally engaged in patches?

We try to be as quick as possible in releasing new _versions_ that fix a given CVE, but we are dependent on the upstreams to correctly fix those, and release a version. There's no policy for anything beyond that, except "best effort".

In this case, the OpenSSL project decided the severity of the CVEs was not high enough to warrant a new release (which, honestly, given the amount of grief this causes, deserves to be critizised; version numbers are cheap, but I digress...), so there's nothing for us to do except backport the fixes, but we _cannot_ encode that fact in the version number, and so whatever CVE-infra you have is still going to see an affected version and keep screaming at you.

> Not quite why NIST & OpenSSL's rating are different. Is this some misclassification by NIST or am I missing something?

There's no absolute scale of the severity of a bug (though that score is trying to pretend there is). Different people can come to different conclusions about how likely a given bug is to be exploited, how relevant the required circumstances are in their environment or threat model, etc.

> Working for a bank & any time we see a high 7.0~ on CVE or CVSS we tag them right away & require (begging?) session(s) with security.

I know the pain. You should point them to OpenSSL's own assessment. Not much to do but wait for another release in the meantime.

> Unfortunately, we can't go to `conda-forge` as it's a user channel.

Ironically, by being able to backport those fixes, conda-forge builds would genuinely be the "safest" option from the POV of those CVEs. But I'm not sure if you can convince your IT security to use conda-forge, and you shouldn't oversell security on that front, because the world is a scary place, and we're a volunteer-run organisation that cannot make security promises.

**Comment by yelled1** [comment]
> because the world is a scary place, and we're a volunteer-run organisation that cannot make security promises.
Even we pay for it through Anaconda we cannot get a promise or timely updates (still on 1.1.1t & no 3.x when 1.1.1 is ending in Sept) or quite a good explanation why divergent NIST vs. OpenSSL's interpretation.

**Comment by ekomarova** [comment]
https://github.com/conda-forge/openssl-feedstock/pull/125

**Comment by h-vetinari** [comment]
> Even we pay for it through Anaconda we cannot get a promise or timely updates (still no 1.1.1t & no 3.x when 1.1.1 is ending in Sept) or quite a good explanation why divergent NIST vs. OpenSSL's interpretation.

You're not going to get a satisfactory explanation why the scores are different, other that people use different methodologies to gauge impact, and can come to different conclusions.

I'm not sure if there's another layer (e.g. an out-of-date proxy) between you and Anaconda, but they [published](https://anaconda.org/anaconda/openssl/files) 1.1.1t over two months ago.

Anaconda also has their hands more than full with keeping everything running (like rebuilding everything for OpenSSL 3), so I personally consider it a defensible position to follow OpenSSL's determination and wait for the new version. As a customer you may disagree and perhaps they manage to prioritize this work to keep the customer happy.

But even though banks have their hair on fire every time a CVE drops, the world doesn't suddenly come to a halt. It's not all so black and white.

**Comment by yelled1** [comment]
I agree after looking into this further:

From its own FAQ, NIST explains it this way: 
“CVSS is an industry standard used to supply a qualitative measure of severity. CVSS is *not* a measure of risk.”
(Not sure why NIST calls this number 'qualitative.' : attempt at a humor?)

A strong recommendation will be made vs using CVE alone to ignite our hair on fire. As we should NOT be engaging welding the doors shut type quarantine over what amounts to a High-Incidence & Low-Consequence issue, which is akin to a common cold.
Only the Double Highs or High-Consequence with suspected incident (like being bitten by a racoon & potentially leading to rabies) should trigger a quarantine. Even with the Double highs, widespread welding should be avoided as much as possible.
Hopefully this works.
BTW: Isn't it good to know Anaconda references this channel for solutions?
